// sidebar
export const SIDEBAR_OPEN = 'SIDEBAR_OPEN'
export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE'

// cards
export const GET_CARDS_BEGIN = 'GET_CARDS_BEGIN'
export const GET_CARDS_SUCCESS = 'GET_CARDS_SUCCESS'
export const GET_CARDS_ERROR = 'GET_CARDS_ERROR'
export const GET_SINGLE_CARD_BEGIN = 'GET_SINGLE_CARD_BEGIN'
export const GET_SINGLE_CARD_SUCCESS = 'GET_SINGLE_CARD_SUCCESS'
export const GET_SINGLE_CARD_ERROR = 'GET_SINGLE_CARD_ERROR'
export const LOAD_CARDS = 'LOAD_CARDS'

// avatars
export const GET_AVATARS_BEGIN = 'GET_AVATARS_BEGIN'
export const GET_AVATARS_SUCCESS = 'GET_AVATARS_SUCCESS'
export const GET_AVATARS_ERROR = 'GET_AVATARS_ERROR'
export const GET_SINGLE_AVATAR_BEGIN = 'GET_SINGLE_AVATAR_BEGIN'
export const GET_SINGLE_AVATAR_SUCCESS = 'GET_SINGLE_AVATAR_SUCCESS'
export const GET_SINGLE_AVATAR_ERROR = 'GET_SINGLE_AVATAR_ERROR'
export const LOAD_AVATAR = 'LOAD_AVATAR'

//filtered view
export const SET_GRIDVIEW = 'SET_GRIDVIEW'
export const SET_LISTVIEW = 'SET_LISTVIEW'
export const UPDATE_SORT = 'UPDATE_SORT'
export const SORT_CARDS = 'SORT_CARDS'
export const UPDATE_FILTERS = 'UPDATE_FILTERS'
export const FILTER_CARDS = 'FILTER_CARDS'
export const CLEAR_FILTERS = 'CLEAR_FILTERS'

// deck
export const ADD_TO_DECK = 'ADD_TO_DECK'
export const REMOVE_FROM_DECK = 'REMOVE_FROM_DECK'
export const TOGGLE_DECK_CARD_AMOUNT = 'TOGGLE_DECK_CARD_AMOUNT'
export const CLEAR_DECK = 'CLEAR_DECK'
export const COUNT_DECK_CARDS_TOTALS = 'COUNT_DECK_CARDS_TOTALS'
